# Generated by Django 5.2.6 on 2025-10-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('confirmpassword', models.CharField()),
                ('countrySelection', models.CharField(choices=[('Usa', 'USA'), ('India', 'INDIA'), ('Canada', 'CANADA')], max_length=25)),
            ],
        ),
    ]
