# Generated by Django 5.2.4 on 2025-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('Manaqger', 'MANaGER'), ('employee', 'EMPLOYEE')], default='employee', max_length=20),
            preserve_default=False,
        ),
    ]
