# Generated by Django 5.2.6 on 2025-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminone', '0002_accountmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='manager',
            field=models.CharField(default='manager', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('Manager', 'MANaGER'), ('employee', 'EMPLOYEE')], max_length=20),
        ),
    ]
