# Generated by Django 5.2.6 on 2025-10-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminone', '0003_accountmodel_manager_alter_accountmodel_role'),
        ('Adminone', '0003_approvalrule_expense'),
    ]

    operations = [
    ]
