# Generated by Django 5.2.6 on 2025-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminone', '0004_merge_20251004_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('Manager', 'MANAGER'), ('employee', 'EMPLOYEE')], max_length=20),
        ),
    ]
